### ISSUE TITLE
Provide a way to specify data when executing a script directly

### ISSUE THREAD

**Issue by tupini07** [erezsh/Preql#8]
When writing a preql script I may want to specify some information I may not have at the moment of writing it (eg, dynamically obtained data from another source). Since it is not possible to directly implement IO operations in preql, I think the next option would be that of implementing the functionality to pass data to the script during execution. 

We should probably include some kind of placeholder syntax in the script to say that a variable is externally provided (I guess their type can always be _string_), and they may potentially also have default values. Something like:

```
external USER_ID = "default value"
```

And as for providing the actual data for these external variables, one (or more) of the following should suffice:

- Pass them as `key=value` pairs when invoking the command
- Read them from an input file (eg, json, ini, etc)
- Read them from environment variables at the moment of executing the script

In all of the above, the name of the key should match exactly the name of the variable. A question here could be whether preql should throw a _compilation_ exception if no value is found for a key. I would vote for _yes_, since it makes the functionality safer.

Not sure if this is possible or how hard it is, but it would make preql much more useful :smile:

**Comment by erezsh** [comment]
Preql is lacking in I/O operations, but it's mostly because I haven't got around to it yet, and not by design.

There is already an `import_csv` function that reads from a file.

I could just add the functions `read_file`, `read_json` and `env_vars` (names pending)

Would that resolve your issue?

(In which case, an error would be raised for a missing key in the json/env)

**Comment by tupini07** [comment]
yes that would be great thank you! I wasn't aware of the existence of `import_csv` (I obviously didn't search for it)

**Comment by erezsh** [comment]
Hi @tupini07,

I implemented the following functions:

- `import_json()` - https://preql.readthedocs.io/en/latest/preql-modules.html#import_json

- `env_vars()` - https://preql.readthedocs.io/en/latest/preql-modules.html#env_vars

For an example of how to use `import_json`, see this example: https://github.com/erezsh/Preql/blob/master/examples/airports.pql

It is now available in the `master ` branch.

**Comment by tupini07** [comment]
That's great! Thanks a lot
