### ISSUE TITLE
whitespace in table name

### ISSUE THREAD

**Issue by v217** [erezsh/Preql#9]
Hi thank you for this great tool!
I don't know how I can deal with witespace in table names?

**Comment by erezsh** [comment]
Hi @v217 , I'm glad you find it useful!

I just pushed to `master` a commit that allows any character in a name, by surrounding it in with backticks:

```javascript
 >> table `a b` {`x y`: int}
 >> new `a b`(5)
Row{id: 1, `x y`: 5}
 >> `a b`
table `a b` =1
┏━━━━┳━━━━━━━┓
┃ id ┃ `x y` ┃
┡━━━━╇━━━━━━━┩
│  1 │     5 │
└────┴───────┘
```

If you can, please make sure that it works for you.

It will be included in the next release.

**Comment by v217** [comment]
Sorry, I wasn't able to install the master branch. 
I tried:

`pipx install --suffix=_master --verbose https://github.com/erezsh/Preql.git@master`

I get this error.



    pipx install --suffix=_master --verbose https://github.com/erezsh/Preql.git@master
    pipx >(setup:704): pipx version is 0.16.0.0
    pipx >(setup:705): Default python interpreter is '/usr/bin/python3'
    pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: https://github.com/erezsh/Preql.git@master
    creating virtual environment...
    pipx >(run_subprocess:120): running /usr/bin/python3 -m venv --without-pip /tmp/tmphi5_utd5
    pipx >(run_subprocess:120): running /tmp/tmphi5_utd5/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
    pipx >(run_subprocess:120): running /home/v/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
    pipx >(run_subprocess:120): running /tmp/tmphi5_utd5/bin/python --version
    determining package name from 'https://github.com/erezsh/Preql.git@master'...
    pipx >(run_subprocess:120): running /tmp/tmphi5_utd5/bin/python -m pip list --format=json
    pipx >(run_subprocess:120): running /tmp/tmphi5_utd5/bin/python -m pip install --no-dependencies https://github.com/erezsh/Preql.git@master
    Collecting https://github.com/erezsh/Preql.git@master
      ERROR: HTTP error 404 while getting https://github.com/erezsh/Preql.git@master
    ERROR: Could not install requirement https://github.com/erezsh/Preql.git@master because of HTTP error 404 Client Error: Not Found for url: https://github.com/erezsh/Preql.git@master for URL https://github.com/erezsh/Preql.git@master
    pipx >(subprocess_post_check:154): '/tmp/tmphi5_utd5/bin/python -m pip install --no-dependencies https://github.com/erezsh/Preql.git@master' failed
    Cannot determine package name from spec
    'https://github.com/erezsh/Preql.git@master'. Check package spec for errors.
    ; pipx install --suffix=_master --verbose https://github.com/erezsh/Preql.git@master
    pipx >(setup:704): pipx version is 0.16.0.0
    pipx >(setup:705): Default python interpreter is '/usr/bin/python3'
    pipx >(_parsed_package_to_package_or_url:128): cleaned package spec: https://github.com/erezsh/Preql.git@master
    creating virtual environment...
    pipx >(run_subprocess:120): running /usr/bin/python3 -m venv --without-pip /tmp/tmpc19n3aw2
    pipx >(run_subprocess:120): running /tmp/tmpc19n3aw2/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
    pipx >(run_subprocess:120): running /home/v/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
    pipx >(run_subprocess:120): running /tmp/tmpc19n3aw2/bin/python --version
    determining package name from 'https://github.com/erezsh/Preql.git@master'...
    pipx >(run_subprocess:120): running /tmp/tmpc19n3aw2/bin/python -m pip list --format=json
    pipx >(run_subprocess:120): running /tmp/tmpc19n3aw2/bin/python -m pip install --no-dependencies https://github.com/erezsh/Preql.git@master
    Collecting https://github.com/erezsh/Preql.git@master
      ERROR: HTTP error 404 while getting https://github.com/erezsh/Preql.git@master
    ERROR: Could not install requirement https://github.com/erezsh/Preql.git@master because of HTTP error 404 Client Error: Not Found for url: https://github.com/erezsh/Preql.git@master for URL https://github.com/erezsh/Preql.git@master
    pipx >(subprocess_post_check:154): '/tmp/tmpc19n3aw2/bin/python -m pip install --no-dependencies https://github.com/erezsh/Preql.git@master' failed
    Cannot determine package name from spec
    'https://github.com/erezsh/Preql.git@master'. Check package spec for errors.

**Comment by v217** [comment]
I installed preql like so:

    pipx install --suffix=_master --verbose git+https://github.com/erezsh/Preql.git@master 

and I get this error:


    preql_master 
    Traceback (most recent call last):
      File "/home/v/.local/bin/preql_master", line 5, in <module>
        from preql.__main__ import main
      File "/home/v/.local/pipx/venvs/preql-lang-master/lib/python3.8/site-packages/preql/__init__.py", line 1, in <module>
        from . import _base_imports
      File "/home/v/.local/pipx/venvs/preql-lang-master/lib/python3.8/site-packages/preql/_base_imports.py", line 1, in <module>
        from . import interp_common, pql_types, pql_objects, types_impl
      File "/home/v/.local/pipx/venvs/preql-lang-master/lib/python3.8/site-packages/preql/interp_common.py", line 8, in <module>
        from . import pql_ast as ast
      File "/home/v/.local/pipx/venvs/preql-lang-master/lib/python3.8/site-packages/preql/pql_ast.py", line 4, in <module>
        from .utils import dataclass, TextReference, field_list
      File "/home/v/.local/pipx/venvs/preql-lang-master/lib/python3.8/site-packages/preql/utils.py", line 16, in <module>
        from .context import Context
    ModuleNotFoundError: No module named 'preql.context'

**Comment by v217** [comment]
There is also one strange thing, probably I am missing an option or flag for the sqlite driver.
I can only open sqlite db files if I commited to the file from sqlite or if I copied with `cp --reflink=never ` on btrfs. Symbolic links and remounts doesn't seem to  work either.

**Comment by erezsh** [comment]
Sorry @v217 it's entirely my fault. Please try now!

**Comment by erezsh** [comment]
> I can only open sqlite db files if I commited to the file from sqlite or if I copied with `cp --reflink=never ` on btrfs. Symbolic links and remounts doesn't seem to work either

That's strange. Does it works if you do it directly from Python?

```python
import sqlite3
conn = sqlite3.connect('example.db')
...
```

**Comment by v217** [comment]
Hi,
Thank you for your fast response!
It doesn't seem to work for loaded tables

    ; preql_master
    Preql 0.1.19 interactive prompt. Type help() for help
     >> connect("sqlite://bb/04.sqlite", load_all_tables:true)
    (INFO) interp -- [Preql] Connecting to sqlite://bb/04.sqlite
     >> `a b`
    Exception traceback:
      ~~~ file '<repl>' line 1, column 1
    `a b`
    ^----    

    NameError: Name '`a b`' not found

**Comment by v217** [comment]
Yes symbolic links work if I use python like in comment https://github.com/erezsh/Preql/issues/9#issuecomment-770839637

    ; python3.8
    Python 3.8.6 (default, Sep 25 2020, 09:36:53) 
    [GCC 10.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import sqlite3
    >>> conn2 = sqlite3.connect('0000.sqlite')
    >>> a=conn2.cursor()
    >>> a.execute("SELECT name FROM sqlite_master WHERE type='table';")
    <sqlite3.Cursor object at 0x7fd175e628f0>
    >>> print(a.fetchall())

**Comment by erezsh** [comment]
> It doesn't seem to work for loaded tables

I accidentally left the quotes in the name, sorry! It should work now. Please try again, and thanks for the patience :)

**Comment by erezsh** [comment]
Symbolic links work for me. The following runs well (on ubuntu, default file system):

```javascript
$ ln -s ~/code/pql/test.db symlink.db
$ preql sqlite:///symlink.db
Preql 0.1.19 interactive prompt. Type help() for help
 >> tables()
              table  =2
┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ name   ┃ type                      ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ primes │ table[id: int?, num: int] │
│ a b    │ table[x y: int?]          │
└────────┴───────────────────────────┘
```

Can you provide a minimal code example that would demonstrate the problem?

**Comment by v217** [comment]
Hi thanks symbolic links work now!

**Comment by v217** [comment]
and whitespaces **work great now**!
Thank you for your help!!
Really happy I found this!

**Comment by erezsh** [comment]
Happy to help!

Thank you for being an early adopter. Please keep opening issues, if you run into any more problems.
